source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }



gem "rails", "~> 7.0.5"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "bcrypt", "~> 3.1.7"
gem "rack-cors"
gem "rack-attack"

# Auth
gem "jwt", "~> 2.7"

# Background jobs
gem "sidekiq", "~> 7.0"

# Redis
gem "redis", "~> 5.0"

# HTTP client (external price API)
gem "faraday", "~> 2.7"
gem "faraday-retry", "~> 2.2"

# Circuit breaker
gem "stoplight", "~> 3.0"

# Serializers
gem "blueprinter", "~> 0.25"

# Pagination
gem "pagy", "~> 6.2"

gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails", "~> 6.2"
  gem "faker", "~> 3.2"
  gem "shoulda-matchers", "~> 5.3"
  gem "webmock", "~> 3.19"
end

group :development do
  gem "annotate"
  gem "bullet"
end

group :test do
  gem "database_cleaner-active_record", "~> 2.1"
  gem "rspec_junit_formatter"
  gem "mock_redis"
end
